<?php 
	if(drupal_is_front_page()) {
		$campus = 'none';
	}
	else if (false !== stripos($_SERVER["REQUEST_URI"], 'eckles')) {
		$campus = 'eckles';
	}
	else if (false !== stripos($_SERVER["REQUEST_URI"], 'virginia')) {
		$campus = 'virginia';
	}
        else if (false !== stripos($_SERVER["REQUEST_URI"], 'utlc')) {
                $campus = 'utlc';
        }
	else {
		$campus = 'gelman';
	}
?>

<?php if ($_SERVER['SERVER_NAME'] == 'gwlibrary-test.wrlc.org' OR $_SERVER['SERVER_NAME'] == 'gwlibrary-staging.wrlc.org' OR $_SERVER['SERVER_NAME'] == 'test.library.gwu.edu'): ?>
    <div class="staging-header-container">
        <div class="staging-header-message">
            <span style="color:#FC2847">WARNING:</span> this is the staging server for GW Libraries and is intended for internal use only. Content, functionality and design may not match the GW Libraries site (<a href="http://library.gwu.edu">library.gwu.edu</a>)
        </div>
    </div>
<?php endif; ?>

<!-- begin topheader -->
<div id='topheader-container'>
  <div id='topheader-content'>

<?php
  $liblogo = $front_page . drupal_get_path('theme', $themename) . "/images/logos/gw_iddol_libraries_wht_rev.png";
  $liblogo_alt = "logo: The George Washington University Libraries";
  $liblink = $front_page;
  $liblink_aria = "GW Libraries home page";
?>

	    <div id='gwlogo-topheader'><a href='<?php print $liblink; ?>' aria-label='<?php print $liblink_aria; ?>'><img width=199 height=90 src='<?php print $liblogo; ?>' alt='<?php print $liblogo_alt; ?>' /><span class="sr-only"><?php print $liblink_aria; ?></span></a>
	    </div>

    <?php if ($campus == 'gelman' OR $campus == 'none'): ?>
    <div id='header-hours'>
      <?php print render($page['topheader_right']); ?>
  <!-- hours grid html will be replaced by block (generated by Hours module) -->
  <!--<div class="container">
    <table>
      <tr>
        <td colspan="7">
        Hours for GWorld Holders
        </td>
      </tr>
      <tr>
        <td>TODAY</td>
        <td>SAT</td>
        <td>SUN</td>
        <td>MON</td>
        <td>TUE</td>
        <td>WED</td>
        <td>THU</td>
      </tr>
      <tr>
        <td>24 hours</td>
        <td>24 hours</td>
        <td>24 hours</td>
        <td>24 hours</td>
        <td>24 hours</td>
        <td>24 hours</td>
        <td>24 hours</td>
      </tr>
      <tr>
        <td colspan="7">
        <a href="/hours/visitors">Visitor Hours</a> &bull; <a href="/hours">Complete Hours Information</a> &bull; <a href="/hours/closures">Holidays and Closures</a>
        </td>
      <tr>
    </table>
    <div class="handheld">
      <div class="handheld-hours">GELMAN: Open 24 hours</div>
      <div class="handheld-hours-links"><a href="/hours">Complete Hours Information</a></div>
    </div>
  </div>-->

    </div>
    <?php elseif ($campus == 'eckles'): ?>
    <div id="eckles-head">
      <a href="<?php print $front_page . 'eckles'; ?>"><img src="<?php print $front_page . drupal_get_path('theme', $themename) . '/images/logos/gw_iddol_eckles_wht_rev_no_gw.png'; ?>" alt="logo: Eckles Library at Mount Vernon Campus"></a>
    </div>
    <?php elseif ($campus == 'virginia'): ?>
    <div id="virginia-head">
      <a href="<?php print $front_page . 'virginia'; ?>"><img src="<?php print $front_page . drupal_get_path('theme', $themename) . '/images/logos/gw_iddol_vstclib_wht_rev_no_gw.png'; ?>" alt="logo: Virginia Science and Technology Campus Library"></a>
    </div>
    <?php endif; ?>

  </div>
</div>

<!-- begin library unit section header -->
<?php
        if($campus == 'none') {
                echo "<div id='libheader-front'>";
        }
        else if ($campus == 'eckles') {
                echo "<div id='libheader-eckles'>";
        }
        else if ($campus == 'virginia') {
                echo "<div id='libheader-virginia'>";
        }
        else if ($campus == 'utlc') {
                echo "<div id='libheader-utlc'>";
        }
        else {
                echo "<div id='libheader-gelman'>";
        }
?>

<div class="sr-only">
                <a href="http://library.gwu.edu/about" itemprop="copyrightNotice">
                    &copy; <span itemprop="copyrightYear"><?php echo date("Y") ?></span><span itemprop="copyrightHolder" itemscope itemtype="http://schema.org/Library" itemid="http://library.gwu.edu"><span itemprop="name"> GW Libraries &amp; Academic Innovation</span></span>
                </a>
</div>

			<section id="banner">
				<div id="innerBannerDiv">				
					<div class="banner-container">	
                                                <?php if($campus == 'utlc'): ?>
                                                <a id="utlcLogoLink" aria-label="University Teaching and Learning Center Main Page" href="<?php print $front_page; ?>utlc">
                                                <div class="utlcLogoLink">
                                                  <img src='<?php print $front_page; ?>sites/all/themes/Libsite7/images/header_logo_utlc.png' alt='logo: UTLC at GW Libraries' />
                                                  <div class="gelmanLogoText">UTLC at Libraries</div>
                                                  <!-- link area to Home -->
                                                </div>
                                                </a>
                                                <?php else: ?> 
                                                  <!-- formerly: libraries logo -->
                                                <?php endif; ?>
						  
						<?php if(drupal_is_front_page()): ?>
                                                  <!-- formerly: rollovers for each library name -->
						<?php endif; ?>
												
						<!-- begin tabbed search block -->
					    <?php if(!drupal_is_front_page() && $campus !== 'utlc'): ?>
					    <div class='search-header'>

							<a id="displaysearchall" href="javascript:togglesearch('searchallbox');"><div id="searchall" class="searchbutton tab-active" onclick="changeClass('searchall')">
							All
							</div></a>

							<a id="displaysearchplus" href="javascript:togglesearch('searchplusbox');"><div id="searchplus" class="searchbutton" onclick="changeClass('searchplus')">
							ArticlesPlus
							</div></a>
							
							<a id="displaysearchcat" href="javascript:togglesearch('searchcatbox');"><div id="searchcat" class="searchbutton" onclick="changeClass('searchcat')">
							Catalog
							</div></a>
							
							<a id="displaysearchjournals" href="javascript:togglesearch('searchjournalsbox');"><div id="searchjournals" class="searchbutton" onclick="changeClass('searchjournals')">
							Journals
							</div></a>

							<a id="displaysearchref" href="javascript:togglesearch('searchrefbox');"><div id="searchref" class="searchbutton" onclick="changeClass('searchref')">
							Reference
							</div></a>
							
							<a id="displaysearchsite" href="javascript:togglesearch('searchsitebox');"><div id="searchsite" class="searchbuttonLast" onclick="changeClass('searchsite')">
							Website
							</div></a>
										
							<!--searchboxes -->

					        <div id="searchallbox" class="searchbox" style="display:block;">

					        	<script>

					        		function getUserQuery(name) {
									    name = name.replace(/[\[]/, "\\\[").replace(/[\]]/, "\\\]");
									    var regexS = "[\\?&]" + name + "=([^&#]*)";
									    var regex = new RegExp(regexS);
									    var results = regex.exec(window.location.href);
									    if (results == null)
									        return "";
									    else
									        return results[1];
									} 

					        		var userQuery = getUserQuery('query');

					        		// window.onload = initThis;

					        		function initThis() {
										document.forms['bento-form'].elements['query'].value = userQuery;
									}

					        	</script>

					            <form method="get" name="bento-form" id="" action="/search-all" onSubmit="ga('send', 'event','tabbed-search','/search-all','Search All');">
					                <input placeholder="search everything (all of our catalogs and the pages of the website)" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" title="enter keywords to search all catalogs and website" type="text" name="query" size="50" value="" id="searchfieldall" maxlength=100 />&nbsp;<input type="submit" value="Search" />
					            </form>
					        </div>

							<div id="searchplusbox" class="searchbox">
								<form action="http://gw.summon.serialssolutions.com/search?" method="get" target="_blank" name="fbanner" onSubmit="ga('send', 'event','tabbed-search','http://gw.summon.serialssolutions.com/search','ArticlesPlus');">
									<label for='searchfieldplus'>enter your search terms for ArticlesPlus</label>
									<input placeholder="search ArticlesPlus for articles &amp; more" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" type="text" value="" id="searchfieldplus" name="s.q" title="enter keywords to search for articles and books" />
									<input type="hidden" value="ContentType,Newspaper Article,t" name="s.fvf[]" />
									<input type="submit" value="Search" />&nbsp;<a href="<?php print $front_page . 'howdoi/aboutarticlesplus'; ?>" id="plustext">more about ArticlesPlus</a>
								</form>
							</div>
							<div id="searchcatbox" class="searchbox">					
								<form name="catalog_search" onsubmit="javascript:validate(document.forms[2],true);ga('send', 'event','tabbed-search','http://findit.library.gwu.edu/catalog/','Catalog');return false;">
									<label for='searchfieldcat'>enter your search terms for the catalog</label>
									<input placeholder="search the catalog for books &amp; more" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" type="text" title="enter keywords" id="searchfieldcat" name="TXT1">
									<label for='IDX1'>catalog search type</label>
				                    <select name='IDX1' title='catalog search type'>
				                        <option value='titlecombined:'>title</option>
				                        <option value='journaltitle:'>journal title</option>
				                        <option value='keyword:' selected>keyword</option>
				                        <option value='author:'>author</option>
				                        <option value='subjectterms:'>subject</option>
				                        <option value='lccallnum:'>call number</option>
				                    </select>
									<input type="submit" value="Search" />&nbsp;<a id="cattext" href="http://findit.library.gwu.edu/advanced/">advanced</a>
								</form>
							</div>
							<div id="searchjournalsbox" class="searchbox">
								<form action="http://findit.library.gwu.edu/" name="SS_EJPSearchForm" target="_blank" onSubmit="ga('send', 'event','tabbed-search','http://findit.library.gwu.edu/','Journals');">
									<input value="1.0" name="V" type="hidden" />
									<input value="100" name="N" type="hidden" />
									<input type="hidden" name="L" value="UZ4UG4LZ9G" />
									<label for='searchfieldjournals'>enter your search terms for journals</label>
									<input placeholder="enter journal title to check for online access" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" type="text" title="enter journal title" name="C" id="searchfieldjournals" />
									<label for='S'>journal search type</label>
									<select name="S" id='S'>
										 <option value="A_T_B">title begins with</option>
										 <option value="A_T_M">title (exact)</option>
										 <option value="T_W_A" selected="selected">title keywords</option>
										 <option value="I_M">ISSN</option>
									</select>
									<input type="submit" value="Search" />
								</form>
							</div>

							<div id="searchrefbox" class="searchbox">			
								<script type="text/javascript">
									function rusearch1(){
										var url="http://proxygw.wrlc.org/login?url=http://refuniv.odyssi.com/cgi-bin/member/search/r?dbs+ruprime:@and+";
										var searchInputEl = document.forms.refsearch1.ruSearchInput1.value;
										var newtab = window.open();
										newtab.location = url + encodeURIComponent(searchInputEl);
										}
								</script>
								<script type="text/javascript">
									function getKeyValue(e,form){
										var key=e.keyCode || e.which;
										if (key==13){
										rusearch1();
											}
										}
								</script>							
								<form name="refsearch1" onSubmit="javascript:rusearch1();ga('send', 'event','tabbed-search','http://proxygw.wrlc.org/login?url=http://refuniv.odyssi.com/cgi-bin/member/search/r?dbs+ruprime:@and+','Reference');return false;">
									<label for='searchfieldref'>enter your search terms for reference</label>
									<input placeholder="search for online reference works" type="text" id="searchfieldref" name="ruSearchInput1" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" title="enter keywords">&nbsp;<input type="submit" value="Search" /> <span id="reftext">encyclopedias & bibliographies</span>
								</form>
							</div>

							<div id="searchsitebox" class="searchbox">						
								<form class="search-form" action="/search/node" method="get" id="search-form" accept-charset="UTF-8" onSubmit="ga('send', 'event','tabbed-search','/search/node','Site Search');">
									<label for='searchfieldsite'>enter your search terms for the website</label>
									<input placeholder="search the pages of this site" title="enter keywords to search the pages of this website" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" type="text" name="keys" class="search_box" id="searchfieldsite" value="" />
									<input type="submit" value="Search" />
									<span id="sitetext">search the site</span>
								</form>
							</div>

						</div><!-- closes <div class='search-header'> -->

						<?php endif; ?>
						<!--end searchboxes-->
						<!-- end tabbed search block -->
						<!-- alternate single search box code for handheld is located in libnav.php -->

					    <?php 
						if(drupal_is_front_page()) {
							print "<div class='front-page-header-variant'>
						<a href='" . $front_page . "'>Estelle<span class='three-libs-smalltype'> and </span>Melvin Gelman Library</a>&nbsp;&#8226;
						<a href='" . $front_page . "eckles/'>Eckles Library<span class='three-libs-smalltype'> at the </span>Mount Vernon Campus</a><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='" . $front_page . "virginia/'>Virginia Science<span class='three-libs-smalltype'> and </span>Technology Campus Library</a>
						</div>";
							}								
						?>			
					</div><!-- closes <div class="banner-container">-->
				</div><!-- closes <div id="innerBannerDiv"> -->
			</section>
		
		</div><!-- closes library specific div set in opening php-->

		<!-- campus libs -->
		<?php 
                if ($campus == 'gelman') {$gelmanArrow = "<i class='fa fa-bookmark-o'></i> ";} else {$gelmanArrow = '';}
                if ($campus == 'eckles') {$ecklesArrow = "<i class='fa fa-bookmark-o'></i> ";} else {$ecklesArrow = '';}
                if ($campus == 'virginia') {$vaArrow = "<i class='fa fa-bookmark-o'></i> ";} else {$vaArrow = '';}
                if ($campus == 'utlc') {$specialClass = 'hide';} else {$specialClass = '';}
                        print "<div id='three-libs-container' class='" . $specialClass . "'>
                        <div id='three-libs'><span id='lib-left'> <a href='" . $front_page . "'>" . $gelmanArrow . "Estelle<span class='three-libs-smalltype'> and </span>Melvin Gelman Library</a></span><span id='lib-center'><a href='" . $front_page . "eckles/'>" . $ecklesArrow . "Eckles Library<span class='three-libs-smalltype'> at the </span>Mount Vernon Campus</a></span><span id='lib-right'><a href='" . $front_page . "virginia/'>" . $vaArrow . "Virginia Science<span class='three-libs-smalltype'> and </span>Technology Campus Library</a></span></div>
                        </div>";
		?>
